trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

parameters:
  - name: domain
    displayName: Domain Name
    type: string
    values:
      - sales
      - associates
      - accounting
      - finance
      - customer
      - nonedw
      - shared

parameters:
  - name: sourceKeyVaultName
    displayName: Source Key Vault Name
    type: string
    default: 'source-keyvault-name'

  - name: targetKeyVaultName
    displayName: Target Key Vault Name
    type: string
    default: 'target-keyvault-name'

variables:
  - name: pool
    value: 'ubuntu-latest'

  - name: azureSubscription
    value: 'vanguard-nonprod-azuredevops.com'

pool:
  vmImage: $(pool)

stages:
  - stage: Deploy
    displayName: 'Deploy'
    jobs:
      - job: runMigration
        displayName: 'Run KeyVault Migration Script'
        steps:
          - task: AzureCLI@2
            displayName: 'Run PowerShell Script'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: pwsh
              scriptLocation: filePath
              scriptPath: '$(Build.SourcesDirectory)/migration.ps1'  # Directly reference the script from the repo
              arguments: '"${{ parameters.sourceKeyVaultName }}" "${{ parameters.targetKeyVaultName }}"'

