parameters:
  - name: vmList
    displayName: 'Azure VM List (comma-separated)'
    type: string
    default: 'VM1,VM2'
 
  - name: action
    displayName: 'Action to perform on VMs'
    type: string
    values:
      - Start
      - Stop
    default: 'Stop'
 
  - name: resourceGroup
    displayName: 'Resource Group Name (optional)'
    type: string
    default: ''
 
variables:
  azureSubscription: 'CarMax'
pool:
  vmImage: 'windows-latest'
 
steps:
 
- task: AzureCLI@2
  displayName: 'Manage Azure VMs via PowerShell script'
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'ps'
    scriptLocation: 'scriptPath'
    scriptPath: 'scripts/manage-vms.ps1'
    arguments: >
      -AzureVMList "${{ parameters.vmList }}"
      -Action "${{ parameters.action }}"
      -ResourceGroupName "${{ parameters.resourceGroup }}"
