trigger: none
 
# schedules:
#  - cron: "0 3 * * *"      # 3 AM UTC = 11 PM ET
#    displayName: "Stop VMs evening"
#    branches:
 #     include:
 #       - main
 #   always: true
 
pool:
  vmImage: ubuntu-latest
 
variables:
  vmDetails: '[{"name": "VM1", "resource_group": "ADMIN"}, {"name": "BI", "resource_group": "REPORTING"}]'
  action: "stop"
  sendEmail: "True"
 
steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
 
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: ''
      KeyVaultName: 'kv'
      SecretsFilter: 'SendGridKey'
      RunAsPreJob: true
 
  - script: |
      python -m pip install --upgrade pip
      pip install azure-identity azure-mgmt-compute sendgrid
    displayName: "Install Dependencies"
 
  - script: |
      python start_stop_vm.py '$(vmDetails)' '$(action)' '$(sendEmail)'
    displayName: "Start VMs"
    env:
    SendGridKey: $(SendGridKey)
